# Generated by Django 5.2.6 on 2025-09-21 16:52

import flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="crew_photo",
            field=models.ImageField(
                null=True, upload_to=flight.models.crew_image_upload_path
            ),
        ),
    ]
