# Generated by Django 5.2.6 on 2025-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_crew_crew_photo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("route", "airplane", "departure_time", "arrival_time"),
                name="unique_route_airplane_departure_time_arrival_time",
            ),
        ),
    ]
