services:
    airport_api:
       build:
           context: .
       ports:
           - "8001:8000"
       volumes:
          - ./:/app
          - media_files:/files/media
       command: > 
          sh -c "
          python manage.py wait_for_db && 
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000
          "
       env_file:
          - .env
       depends_on:
          - airport_api_db

    airport_api_db:
       image: postgres:16.0-alpine3.17
       restart: always
       ports:
         - "5432:5432"
       environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
       volumes:
         - my_airport_api_db:$PGDATA

volumes:
  my_airport_api_db:
  media_files:
